name: local-translator-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Package source code into a ZIP file
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out repository
      - name: Check out source code
        uses: actions/checkout@v4
      # Step 2: Upload as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: |
            ./
          if-no-files-found: error
